### ISSUE TITLE
ElasticCache metrics returning 0 values for all metrics

### ISSUE THREAD

**Issue by macadminrohit** [omni-lchen/zabbix-cloudwatch#14]
As per the AWS documentation for getting the Cloudwatch metrics for Elastic cache data we need to provide the CacheClusterId and CacheNodeId both. But in this solution we are only supplying the CacheClusterID and not CacheNodeID. And when are getting 0 values for all the metrics.

**Comment by omni-lchen** [comment]
Please check the Elasticcache dimensions in AWS, if the metrics in a node is the same as cluster, you can tweak the bash wrapper and add additional dimensions, e.g. -d "CacheClusterId=$CLUSTER_ID,CacheNodeID=$CacheNodeID", otherwise you have to add a new function in the zabbix-cloudwatch script to adapt to it.

**Comment by macadminrohit** [comment]
Thanks for the solution.
